### ISSUE TITLE
Error in the console after closing Blender

### ISSUE THREAD

**Issue by xan2622** [jiggymoon69/node_tabber#5]
Blender version: 2.91 official
Add-on version: 0. 1. 4

Hi.
I launch Blender in command line. This allows me to see errors that appear in the console.
When I close Blender, I can see this error: 

```
Exception in module unregister(): 'C:\\Users\\Sebastien\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\node_tabber\\__init__.py'
Traceback (most recent call last):
  File "E:\blender_Portable\2.91\scripts\modules\addon_utils.py", line 434, in disable
    mod.unregister()
  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\node_tabber\__init__.py", line 148, in unregister
    km.keymap_items.remove(kmi)
RuntimeError: Error: KeyMapItem 'NODE_OT_add_tabber_search' cannot be removed from 'Node Editor'
```

**Comment by xan2622** [comment]
There's a reasonably high probability that the error is only on my end. 
Closing the issue for now (until the error re-appears).
